
/**
* ArytmetykaOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Arytmetyka.idl
* Saturday, 29 May 2021 14:12:45 o'clock CEST
*/

public interface ArytmetykaOperations 
{
  double s1 ();
  void s1 (double newS1);
  double s2 ();
  void s2 (double newS2);
  double wynik ();
  void wynik (double newWynik);
  void suma ();
  void roznica ();
  void iloczyn ();
  void iloraz () throws ArytmetykaPackage.DzieleniePrzezZero;
} // interface ArytmetykaOperations
