package ArytmetykaPackage;


/**
* ArytmetykaPackage/DzieleniePrzezZero.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Arytmetyka.idl
* Saturday, 29 May 2021 14:12:45 o'clock CEST
*/

public final class DzieleniePrzezZero extends org.omg.CORBA.UserException
{

  public DzieleniePrzezZero ()
  {
    super(DzieleniePrzezZeroHelper.id());
  } // ctor


  public DzieleniePrzezZero (String $reason)
  {
    super(DzieleniePrzezZeroHelper.id() + "  " + $reason);
  } // ctor

} // class DzieleniePrzezZero
