package ArytmetykaPackage;

/**
* ArytmetykaPackage/DzieleniePrzezZeroHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Arytmetyka.idl
* Saturday, 29 May 2021 14:12:45 o'clock CEST
*/

public final class DzieleniePrzezZeroHolder implements org.omg.CORBA.portable.Streamable
{
  public ArytmetykaPackage.DzieleniePrzezZero value = null;

  public DzieleniePrzezZeroHolder ()
  {
  }

  public DzieleniePrzezZeroHolder (ArytmetykaPackage.DzieleniePrzezZero initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ArytmetykaPackage.DzieleniePrzezZeroHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ArytmetykaPackage.DzieleniePrzezZeroHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ArytmetykaPackage.DzieleniePrzezZeroHelper.type ();
  }

}
