
/**
* _BookstoreImplBase.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Bookstore.idl
* Wednesday, 2 June 2021 14:19:51 o'clock CEST
*/

public abstract class _BookstoreImplBase extends org.omg.CORBA.portable.ObjectImpl
                implements Bookstore, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors
  public _BookstoreImplBase ()
  {
  }

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("_get_bookList", new java.lang.Integer (0));
    _methods.put ("_set_bookList", new java.lang.Integer (1));
    _methods.put ("_get_bookTitlesList", new java.lang.Integer (2));
    _methods.put ("_set_bookTitlesList", new java.lang.Integer (3));
    _methods.put ("_get_sum", new java.lang.Integer (4));
    _methods.put ("_set_sum", new java.lang.Integer (5));
    _methods.put ("_get_discount", new java.lang.Integer (6));
    _methods.put ("_set_discount", new java.lang.Integer (7));
    _methods.put ("discountPrices", new java.lang.Integer (8));
    _methods.put ("sumPrices", new java.lang.Integer (9));
    _methods.put ("listTitlesFromGenre", new java.lang.Integer (10));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Bookstore/_get_bookList
       {
         Book $result[] = null;
         $result = this.bookList ();
         out = $rh.createReply();
         BooksHelper.write (out, $result);
         break;
       }

       case 1:  // Bookstore/_set_bookList
       {
         Book newBookList[] = BooksHelper.read (in);
         this.bookList (newBookList);
         out = $rh.createReply();
         break;
       }

       case 2:  // Bookstore/_get_bookTitlesList
       {
         String $result[] = null;
         $result = this.bookTitlesList ();
         out = $rh.createReply();
         bookTitlesListHelper.write (out, $result);
         break;
       }

       case 3:  // Bookstore/_set_bookTitlesList
       {
         String newBookTitlesList[] = bookTitlesListHelper.read (in);
         this.bookTitlesList (newBookTitlesList);
         out = $rh.createReply();
         break;
       }

       case 4:  // Bookstore/_get_sum
       {
         double $result = (double)0;
         $result = this.sum ();
         out = $rh.createReply();
         out.write_double ($result);
         break;
       }

       case 5:  // Bookstore/_set_sum
       {
         double newSum = in.read_double ();
         this.sum (newSum);
         out = $rh.createReply();
         break;
       }

       case 6:  // Bookstore/_get_discount
       {
         double $result = (double)0;
         $result = this.discount ();
         out = $rh.createReply();
         out.write_double ($result);
         break;
       }

       case 7:  // Bookstore/_set_discount
       {
         double newDiscount = in.read_double ();
         this.discount (newDiscount);
         out = $rh.createReply();
         break;
       }

       case 8:  // Bookstore/discountPrices
       {
         this.discountPrices ();
         out = $rh.createReply();
         break;
       }

       case 9:  // Bookstore/sumPrices
       {
         this.sumPrices ();
         out = $rh.createReply();
         break;
       }

       case 10:  // Bookstore/listTitlesFromGenre
       {
         String genre = in.read_string ();
         this.listTitlesFromGenre (genre);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Bookstore:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }


} // class _BookstoreImplBase
