
/**
* BookstoreHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Bookstore.idl
* Wednesday, 2 June 2021 14:19:51 o'clock CEST
*/

abstract public class BookstoreHelper
{
  private static String  _id = "IDL:Bookstore:1.0";

  public static void insert (org.omg.CORBA.Any a, Bookstore that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Bookstore extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (BookstoreHelper.id (), "Bookstore");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Bookstore read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_BookstoreStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Bookstore value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static Bookstore narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Bookstore)
      return (Bookstore)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _BookstoreStub stub = new _BookstoreStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static Bookstore unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Bookstore)
      return (Bookstore)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _BookstoreStub stub = new _BookstoreStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
