
/**
* BookstoreHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Bookstore.idl
* Wednesday, 2 June 2021 14:19:51 o'clock CEST
*/

public final class BookstoreHolder implements org.omg.CORBA.portable.Streamable
{
  public Bookstore value = null;

  public BookstoreHolder ()
  {
  }

  public BookstoreHolder (Bookstore initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = BookstoreHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    BookstoreHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return BookstoreHelper.type ();
  }

}
