
/**
* BooksHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Bookstore.idl
* Wednesday, 2 June 2021 14:19:51 o'clock CEST
*/

public final class BooksHolder implements org.omg.CORBA.portable.Streamable
{
  public Book value[] = null;

  public BooksHolder ()
  {
  }

  public BooksHolder (Book[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = BooksHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    BooksHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return BooksHelper.type ();
  }

}
